//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SevenMouths.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Share))]
    public partial class Comment: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int CommentId
        {
            get { return _commentId; }
            set
            {
                if (_commentId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CommentId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _commentId = value;
                    OnPropertyChanged("CommentId");
                }
            }
        }
        private int _commentId;
    
        [DataMember]
        public int ShareId
        {
            get { return _shareId; }
            set
            {
                if (_shareId != value)
                {
                    ChangeTracker.RecordOriginalValue("ShareId", _shareId);
                    if (!IsDeserializing)
                    {
                        if (share != null && share.ShareId != value)
                        {
                            share = null;
                        }
                    }
                    _shareId = value;
                    OnPropertyChanged("ShareId");
                }
            }
        }
        private int _shareId;
    
        [DataMember]
        public Nullable<int> ParentId
        {
            get { return _parentId; }
            set
            {
                if (_parentId != value)
                {
                    _parentId = value;
                    OnPropertyChanged("ParentId");
                }
            }
        }
        private Nullable<int> _parentId;
    
        [DataMember]
        public Nullable<float> Grade
        {
            get { return _grade; }
            set
            {
                if (_grade != value)
                {
                    _grade = value;
                    OnPropertyChanged("Grade");
                }
            }
        }
        private Nullable<float> _grade;
    
        [DataMember]
        public byte[] Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private byte[] _description;
    
        [DataMember]
        public Nullable<int> CommentedBy
        {
            get { return _commentedBy; }
            set
            {
                if (_commentedBy != value)
                {
                    _commentedBy = value;
                    OnPropertyChanged("CommentedBy");
                }
            }
        }
        private Nullable<int> _commentedBy;
    
        [DataMember]
        public Nullable<System.DateTime> CommentedAt
        {
            get { return _commentedAt; }
            set
            {
                if (_commentedAt != value)
                {
                    _commentedAt = value;
                    OnPropertyChanged("CommentedAt");
                }
            }
        }
        private Nullable<System.DateTime> _commentedAt;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Share share
        {
            get { return _share; }
            set
            {
                if (!ReferenceEquals(_share, value))
                {
                    var previousValue = _share;
                    _share = value;
                    Fixupshare(previousValue);
                    OnNavigationPropertyChanged("share");
                }
            }
        }
        private Share _share;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            share = null;
        }

        #endregion
        #region Association Fixup
    
        private void Fixupshare(Share previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.comments.Contains(this))
            {
                previousValue.comments.Remove(this);
            }
    
            if (share != null)
            {
                if (!share.comments.Contains(this))
                {
                    share.comments.Add(this);
                }
    
                ShareId = share.ShareId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("share")
                    && (ChangeTracker.OriginalValues["share"] == share))
                {
                    ChangeTracker.OriginalValues.Remove("share");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("share", previousValue);
                }
                if (share != null && !share.ChangeTracker.ChangeTrackingEnabled)
                {
                    share.StartTracking();
                }
            }
        }

        #endregion
    }
}
