//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace SevenMouths.Models
{
    public partial class sevenmouths_dboEntities : ObjectContext
    {
        public const string ConnectionString = "name=sevenmouths_dboEntities";
        public const string ContainerName = "sevenmouths_dboEntities";
    
        #region Constructors
    
        public sevenmouths_dboEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public sevenmouths_dboEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public sevenmouths_dboEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Category> Categories1
        {
            get { return _categories1  ?? (_categories1 = CreateObjectSet<Category>("Categories1")); }
        }
        private ObjectSet<Category> _categories1;
    
        public ObjectSet<Comment> Comments1
        {
            get { return _comments1  ?? (_comments1 = CreateObjectSet<Comment>("Comments1")); }
        }
        private ObjectSet<Comment> _comments1;
    
        public ObjectSet<Cosite> Cosites1
        {
            get { return _cosites1  ?? (_cosites1 = CreateObjectSet<Cosite>("Cosites1")); }
        }
        private ObjectSet<Cosite> _cosites1;
    
        public ObjectSet<CositeUser> CositeUsers1
        {
            get { return _cositeUsers1  ?? (_cositeUsers1 = CreateObjectSet<CositeUser>("CositeUsers1")); }
        }
        private ObjectSet<CositeUser> _cositeUsers1;
    
        public ObjectSet<Picture> Pictures1
        {
            get { return _pictures1  ?? (_pictures1 = CreateObjectSet<Picture>("Pictures1")); }
        }
        private ObjectSet<Picture> _pictures1;
    
        public ObjectSet<Role> Roles1
        {
            get { return _roles1  ?? (_roles1 = CreateObjectSet<Role>("Roles1")); }
        }
        private ObjectSet<Role> _roles1;
    
        public ObjectSet<ShareCategory> ShareCategories1
        {
            get { return _shareCategories1  ?? (_shareCategories1 = CreateObjectSet<ShareCategory>("ShareCategories1")); }
        }
        private ObjectSet<ShareCategory> _shareCategories1;
    
        public ObjectSet<SharePicture> SharePictures1
        {
            get { return _sharePictures1  ?? (_sharePictures1 = CreateObjectSet<SharePicture>("SharePictures1")); }
        }
        private ObjectSet<SharePicture> _sharePictures1;
    
        public ObjectSet<Share> Shares1
        {
            get { return _shares1  ?? (_shares1 = CreateObjectSet<Share>("Shares1")); }
        }
        private ObjectSet<Share> _shares1;
    
        public ObjectSet<UserRole> UserRoles1
        {
            get { return _userRoles1  ?? (_userRoles1 = CreateObjectSet<UserRole>("UserRoles1")); }
        }
        private ObjectSet<UserRole> _userRoles1;
    
        public ObjectSet<User> Users1
        {
            get { return _users1  ?? (_users1 = CreateObjectSet<User>("Users1")); }
        }
        private ObjectSet<User> _users1;
    
        public ObjectSet<Vote> Votes1
        {
            get { return _votes1  ?? (_votes1 = CreateObjectSet<Vote>("Votes1")); }
        }
        private ObjectSet<Vote> _votes1;

        #endregion
    }
}
